list_data <- list(c("Ram","Sham","Raj"), matrix(c(40,80,60,70,90,80), nrow = 2), list("BCA","MCA","BSc"))
names(list_data) <- c("Student", "Marks", "Course")
print(list_data["Student"])
print(list_data$Marks)
print(list_data)